require 'open-uri'
require 'pry'
require 'nokogiri'
require_relative './museum_shows/version.rb'
require_relative './command_line.rb'
require_relative './museum.rb'
require_relative './scraper.rb'
require_relative './exhibit.rb'
